#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

help() {
    echo "Usage: gen.sh [options]"
    echo "Options:"
    echo "  -h, --help      Show this help message and exit"
    echo "  -v, --verbose   Enable verbose output"
    echo "  --rebuild       Purge tmp/emqx and rebuild"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            help
            exit 0
            ;;
        -v|--verbose)
            set -x
            shift
            ;;
        --rebuild)
            REBUILD=true
            shift
            ;;
        v*)
            export PROFILE='emqx'
            VERSION="${1}"
            shift
            ;;
        e*)
            export PROFILE='emqx-enterprise'
            VERSION="${1}"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [[ -z "${VERSION:-}" ]]; then
    help
    exit 1
fi

mkdir -p tmp
pushd tmp
if [ ! -d emqx ] || [ "${REBUILD:-}" = true ]; then
    rm -rf emqx
    git clone "https://github.com/emqx/emqx.git" -b "${VERSION}" --depth 1
    cd emqx
    env PROFILE="${PROFILE}" make
fi
popd
INPUT_DIR="$(pwd)/tmp/emqx/_build/docgen/${PROFILE}"
OUTPUT_DIR="$(pwd)/dist/${PROFILE}/${VERSION}"
mkdir -p $OUTPUT_DIR

dot_json_to_dot_html () {
  local input_file="$1"
  local base_name
  base_name="$(basename "$input_file" .json)"
  echo "${base_name}.html"
}

build() {
    local input_json="$1"
    local output_dir="$2"
    local output_file
    output_file="$(dot_json_to_dot_html $input_json)"
    docker run --rm -it \
        -v "${input_json}:/hsv/public/schemas/default.json" \
        -v "${output_dir}:/out" \
        -e OUTPUT_FILE="/out/${output_file}" \
        "zmstone/hocon-schema-viewer:0.4.1"
}

build_lang() {
    lang="$1"
    cp "$INPUT_DIR/schema-${lang}.json" "$OUTPUT_DIR"/
    build "$OUTPUT_DIR/schema-${lang}.json" "$OUTPUT_DIR"
}

langs=("en" "zh")

for lang in "${langs[@]}"; do
    build_lang "$lang"
done
