#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

help() {
    echo "Usage: gen.sh [options] <emqx-version>"
    echo "Options:"
    echo "  -h, --help      Show this help message and exit"
    echo "  -v, --verbose   Enable verbose output"
    echo "  --rebuild       Purge tmp/emqx and rebuild"
    echo "  --git_repo      Git repo url to clone"
    echo "  --git_ref       Git tag or branch name to clone"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            help
            exit 0
            ;;
        -v|--verbose)
            set -x
            shift
            ;;
        --rebuild)
            REBUILD=true
            shift
            ;;
        --git_ref)
            GIT_REF="${2}"
            shift 2
            ;;
        --git_repo)
            GIT_REPO="${2}"
            shift 2
            ;;
        v*)
            export PROFILE='emqx'
            VERSION="${1}"
            DEFAULT_REPO="https://github.com/emqx/emqx.git"
            shift
            ;;
        e*)
            export PROFILE='emqx-enterprise'
            VERSION="${1}"
            DEFAULT_REPO="https://github.com/emqx/emqx.git"
            shift
            ;;
        6.*)
            export PROFILE='emqx-enterprise'
            VERSION="${1}"
            DEFAULT_REPO="https://github.com/emqx/emqx.git"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [[ -z "${VERSION:-}" ]]; then
    help
    exit 1
fi

if [[ -z "${GIT_REF:-}" ]]; then
    GIT_REF="${VERSION}"
fi

if [[ -z "${GIT_REPO:-}" ]]; then
    GIT_REPO="$DEFAULT_REPO"
fi

case "$VERSION" in
    e5.8.*)
        BUILDER="${EMQX_BUILDER:-ghcr.io/emqx/emqx-builder/6.0-9:1.15.7-26.2.5.14-1-ubuntu22.04}"
        ;;
    6.1.*)
        BUILDER="${EMQX_BUILDER:-ghcr.io/emqx/emqx-builder/6.0-9:1.19.1-28.2-2-ubuntu22.04}"
        ;;
    *)
        BUILDER="${EMQX_BUILDER:-ghcr.io/emqx/emqx-builder/5.6-3:1.18.3-27.3.4.2-4-ubuntu24.04}"
        ;;
esac
mkdir -p tmp
pushd tmp
if [ ! -d emqx ] || [ "${REBUILD:-}" = true ]; then
    rm -rf emqx
    git clone "${GIT_REPO}" -b "${GIT_REF}" --depth 1 ./emqx
    chmod -R u+w ./emqx
    docker run --rm -t -v "$(pwd)"/emqx:/emqx \
        -u $(id -u):$(id -g) \
        -w /emqx \
        -e PROFILE="$PROFILE" \
        -e REBAR_CACHE_DIR='/emqx' \
        -e MIX_HOME='/emqx/.mix' \
        -e HEX_HOME='/emqx/.hex' \
        -e RUSTUP_HOME='/emqx/.rustup' \
        -e CARGO_HOME='/emqx/.cargo' \
        --name docgen \
        "$BUILDER" \
        bash -c "git config --local --add safe.directory /emqx && make"
fi
popd
INPUT_DIR="$(pwd)/tmp/emqx/_build/docgen/${PROFILE}"
OUTPUT_DIR="$(pwd)/docs/"
OUTPUT_DIR_V2="$(pwd)/docs-v2/"

copy_lang() {
    lang="$1"
    cp "$INPUT_DIR/schema-${lang}.json" "${OUTPUT_DIR}/${lang}/${VERSION}.json"
    cp "$INPUT_DIR"/sch*-v2-"${lang}.json" "${OUTPUT_DIR_V2}/${lang}/${VERSION}.json"
}

langs=("en" "zh")

for lang in "${langs[@]}"; do
    copy_lang "$lang"
done

./refresh-index-page.sh
