#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

help() {
    echo "Usage: gen.sh [options] <emqx-version>"
    echo "Options:"
    echo "  -h, --help      Show this help message and exit"
    echo "  -v, --verbose   Enable verbose output"
    echo "  --rebuild       Purge tmp/emqx and rebuild"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            help
            exit 0
            ;;
        -v|--verbose)
            set -x
            shift
            ;;
        --rebuild)
            REBUILD=true
            shift
            ;;
        v*)
            export PROFILE='emqx'
            VERSION="${1}"
            shift
            ;;
        e*)
            export PROFILE='emqx-enterprise'
            VERSION="${1}"
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

if [[ -z "${VERSION:-}" ]]; then
    help
    exit 1
fi

mkdir -p tmp
pushd tmp
if [ ! -d emqx ] || [ "${REBUILD:-}" = true ]; then
    rm -rf emqx
    git clone "https://github.com/emqx/emqx.git" -b "${VERSION}" --depth 1
    cd emqx
    env PROFILE="${PROFILE}" make
fi
popd
INPUT_DIR="$(pwd)/tmp/emqx/_build/docgen/${PROFILE}"
OUTPUT_DIR="$(pwd)/docs/"

copy_lang() {
    lang="$1"
    cp "$INPUT_DIR/schema-${lang}.json" "${OUTPUT_DIR}/${lang}/${VERSION}.json"
}

langs=("en" "zh")

for lang in "${langs[@]}"; do
    copy_lang "$lang"
done

./refresh-index-page.sh
